var myData = [ /*the list of races here pulls from the 2026 All State
    Mastersheet, will add more eventually but am going off of this
    so I don't have to put in a billion races */
    ["-- State --", "-- Office --", "-- Jurisdiction --"],
    ["Alabama", "U.S House","CD-01"],
    ["Alabama", "U.S House","CD-02"],
    ["Alabama", "U.S House","CD-03"],
    ["Alabama", "U.S House","CD-04"],
    ["Alabama", "U.S House","CD-05"],
    ["Alabama", "U.S House","CD-06"],
    ["Alabama", "U.S House","CD-07"],
    ["Alabama", "U.S Senate","Statewide"],
    ["Alabama", "Governor","Statewide"],
    ["Alabama", "Lieutenant Governor","Statewide"],
    ["Alabama", "Attorney General","Statewide"],
    ["Alabama", "Secretary of State","Statewide"],
    ["Alabama", "Treasurer","Statewide"],
    ["Alabama", "Auditor","Statewide"],
    ["Alabama", "Commissioner of Agriculture","Statewide"],
    ["Alabama", "Supreme Court","S1"],
    ["Alabama", "Supreme Court","S2"],
    ["Alabama", "Supreme Court","S8"],
    ["Alabama", "Court of Civil Appeals","S4"],
    ["Alabama", "Court of Civil Appeals","S5"],
    ["Alabama", "Court of Criminal Appeals","S4"],
    ["Alabama", "Court of Criminal Appeals","S5"],
    ["Alabama", "Board of Education","D2"],
    ["Alabama", "Board of Education","D4"],
    ["Alabama", "Board of Education","D6"],
    ["Alabama", "Board of Education","D8"],
    ["Alabama", "Public Service Commission","P1"],
    ["Alabama", "Public Service Commission","P2"],

    ["Alaska", "U.S House","At-Large"],
    ["Alaska", "U.S Senate","Statewide"],
    ["Alaska", "Governor","Statewide"],

    ["Arizona", "U.S House","CD-01"],
    ["Arizona", "U.S House","CD-02"],
    ["Arizona", "U.S House","CD-03"],
    ["Arizona", "U.S House","CD-04"],
    ["Arizona", "U.S House","CD-05"],
    ["Arizona", "U.S House","CD-06"],
    ["Arizona", "U.S House","CD-07"],
    ["Arizona", "U.S House","CD-08"],
    ["Arizona", "U.S House","CD-09"],
    ["Arizona", "U.S Senate","Statewide"],
    ["Arizona", "Governor","Statewide"],
    ["Arizona", "Lieutenant Governor","Statewide"],
    ["Arizona", "Attorney General","Statewide"],
    ["Arizona", "Secretary of State","Statewide"],

    ["Arkansas", "U.S House","CD-01"],
    ["Arkansas", "U.S House","CD-02"],
    ["Arkansas", "U.S House","CD-03"],
    ["Arkansas", "U.S House","CD-04"],
    ["Arkansas", "U.S Senate","Statewide"],
    ["Arkansas", "Governor","Statewide"],
    ["Arkansas", "Lieutenant Governor","Statewide"],
    ["Arkansas", "Attorney General","Statewide"],
    ["Arkansas", "Secretary of State","Statewide"],
    ["Arkansas", "Auditor","Statewide"],
    ["Arkansas", "Commissioner of State Lands","Statewide"],
    ["Arkansas", "Treasurer","Statewide"],
    
    ["California", "U.S House","CD-01"],
    ["California", "U.S House","CD-02"],
    ["California", "U.S House","CD-03"],
    ["California", "U.S House","CD-04"],
    ["California", "U.S House","CD-05"],
    ["California", "U.S House","CD-06"],
    ["California", "U.S House","CD-07"],
    ["California", "U.S House","CD-08"],
    ["California", "U.S House","CD-09"],
    ["California", "U.S House","CD-10"],
    ["California", "U.S House","CD-11"],
    ["California", "U.S House","CD-12"],
    ["California", "U.S House","CD-13"],
    ["California", "U.S House","CD-14"],
    ["California", "U.S House","CD-15"],
    ["California", "U.S House","CD-16"],
    ["California", "U.S House","CD-17"],
    ["California", "U.S House","CD-18"],
    ["California", "U.S House","CD-19"],
    ["California", "U.S House","CD-20"],
    ["California", "U.S House","CD-21"],
    ["California", "U.S House","CD-22"],
    ["California", "U.S House","CD-23"],
    ["California", "U.S House","CD-24"],
    ["California", "U.S House","CD-25"],
    ["California", "U.S House","CD-26"],
    ["California", "U.S House","CD-27"],
    ["California", "U.S House","CD-28"],
    ["California", "U.S House","CD-29"],
    ["California", "U.S House","CD-30"],
    ["California", "U.S House","CD-31"],
    ["California", "U.S House","CD-32"],
    ["California", "U.S House","CD-33"],
    ["California", "U.S House","CD-34"],
    ["California", "U.S House","CD-35"],
    ["California", "U.S House","CD-36"],
    ["California", "U.S House","CD-37"],
    ["California", "U.S House","CD-38"],
    ["California", "U.S House","CD-39"],
    ["California", "U.S House","CD-40"],
    ["California", "U.S House","CD-41"],
    ["California", "U.S House","CD-42"],
    ["California", "U.S House","CD-43"],
    ["California", "U.S House","CD-44"],
    ["California", "U.S House","CD-45"],
    ["California", "U.S House","CD-46"],
    ["California", "U.S House","CD-47"],
    ["California", "U.S House","CD-48"],
    ["California", "U.S House","CD-49"],
    ["California", "U.S House","CD-50"],
    ["California", "U.S House","CD-51"],
    ["California", "U.S House","CD-52"],
    ["California", "U.S Senate","Statewide"],
    ["California", "Governor","Statewide"],
    ["California", "Lieutenant Governor","Statewide"],
    ["California", "Secretary of State","Statewide"],
    ["California", "Attorney General","Statewide"],
    ["California", "Treasurer","Statewide"],
    ["California", "State Controller","Statewide"],
    ["California", "Insurance Commissioner","Statewide"],
    ["California", "Board of Equalization","Statewide"],
    
    ["Colorado", "U.S House","CD-01"],
    ["Colorado", "U.S House","CD-02"],
    ["Colorado", "U.S House","CD-03"],
    ["Colorado", "U.S House","CD-04"],
    ["Colorado", "U.S House","CD-05"],
    ["Colorado", "U.S House","CD-06"],
    ["Colorado", "U.S House","CD-07"],
    ["Colorado", "U.S House","CD-08"],
    ["Colorado", "U.S Senate","Statewide"],
    ["Colorado", "Governor","Statewide"],
    ["Colorado", "Lieutenant Governor","Statewide"],
    ["Colorado", "Secretary of State","Statewide"],
    ["Colorado", "Attorney General","Statewide"],
    ["Colorado", "Treasurer","Statewide"],
    ["Colorado", "State Board of Education","D1"],
    ["Colorado", "State Board of Education","D3"],
    ["Colorado", "State Board of Education","D7"],
    ["Colorado", "State Board of Regents","D2"],
    ["Colorado", "State Board of Regents","D6"],
    ["Colorado", "State Board of Regents","D7"],

    ["Connecticut", "U.S House","CD-01"],
    ["Connecticut", "U.S House","CD-02"],
    ["Connecticut", "U.S House","CD-03"],
    ["Connecticut", "U.S House","CD-04"],
    ["Connecticut", "U.S House","CD-05"],
    ["Connecticut", "U.S Senate","Statewide"],
    ["Connecticut", "Governor","Statewide"],
    ["Connecticut", "Lieutenant Governor","Statewide"],
    ["Connecticut", "Attorney General","Statewide"],
    ["Connecticut", "Secretary of State","Statewide"],
    ["Connecticut", "Comptroller","Statewide"],
    ["Connecticut", "Treasurer","Statewide"],

    ["Delaware", "U.S House","At-Large"],
    ["Delaware", "U.S Senate","Statewide"],
    ["Delaware", "Governor","Statewide"],
    ["Delaware", "Lieutenant Governor","Statewide"],
    ["Delaware", "Auditor","Statewide"],
    ["Delaware", "Treasurer","Statewide"],

    ["Florida", "U.S House","CD-01"],
    ["Florida", "U.S House","CD-02"],
    ["Florida", "U.S House","CD-03"],
    ["Florida", "U.S House","CD-04"],
    ["Florida", "U.S House","CD-05"],
    ["Florida", "U.S House","CD-06"],
    ["Florida", "U.S House","CD-07"],
    ["Florida", "U.S House","CD-08"],
    ["Florida", "U.S House","CD-09"],
    ["Florida", "U.S House","CD-10"],
    ["Florida", "U.S House","CD-11"],
    ["Florida", "U.S House","CD-12"],
    ["Florida", "U.S House","CD-13"],
    ["Florida", "U.S House","CD-14"],
    ["Florida", "U.S House","CD-15"],
    ["Florida", "U.S House","CD-16"],
    ["Florida", "U.S House","CD-17"],
    ["Florida", "U.S House","CD-18"],
    ["Florida", "U.S House","CD-19"],
    ["Florida", "U.S House","CD-20"],
    ["Florida", "U.S House","CD-21"],
    ["Florida", "U.S House","CD-22"],
    ["Florida", "U.S House","CD-23"],
    ["Florida", "U.S House","CD-24"],
    ["Florida", "U.S House","CD-25"],
    ["Florida", "U.S House","CD-26"],
    ["Florida", "U.S House","CD-27"],
    ["Florida", "U.S House","CD-28"],
    ["Florida", "U.S Senate","Statewide"],
    ["Florida", "Governor","Statewide"],
    ["Florida", "Lieutenant Governor","Statewide"],
    ["Florida", "Attorney General","Statewide"],
    ["Florida", "Agriculture Commissioner","Statewide"],
    ["Florida", "Treasurer","Statewide"],
    ["Florida", "Supreme Court","Statewide"],

    ["Georgia", "U.S House","CD-01"],
    ["Georgia", "U.S House","CD-02"],
    ["Georgia", "U.S House","CD-03"],
    ["Georgia", "U.S House","CD-04"],
    ["Georgia", "U.S House","CD-05"],
    ["Georgia", "U.S House","CD-06"],
    ["Georgia", "U.S House","CD-07"],
    ["Georgia", "U.S House","CD-08"],
    ["Georgia", "U.S House","CD-09"],
    ["Georgia", "U.S House","CD-10"],
    ["Georgia", "U.S House","CD-11"],
    ["Georgia", "U.S House","CD-12"],
    ["Georgia", "U.S House","CD-13"],
    ["Georgia", "U.S House","CD-14"],
    ["Georgia", "U.S Senate","Statewide"],
    ["Georgia", "Governor","Statewide"],
    ["Georgia", "Lieutenant Governor","Statewide"],
    ["Georgia", "Attorney General","Statewide"],
    ["Georgia", "Secretary of State","Statewide"],
    ["Georgia", "Agriculture Commissioner","Statewide"],
    ["Georgia", "Insurance and Fire Safety Commissioner","Statewide"],
    ["Georgia", "Labor Commissioner","Statewide"],
    ["Georgia", "Superintendent of Pubilic Instruction","Statewide"],
    ["Georgia", "Public Service Commission","D3"],
    ["Georgia", "Public Service Commission","D5"],

    ["Hawaii", "U.S House","CD-01"],
    ["Hawaii", "U.S House","CD-02"],
    ["Hawaii", "U.S Senate","Statewide"],
    ["Hawaii", "Governor","Statewide"],
    ["Hawaii", "Lieutenant Governor","Statewide"],
    ["Hawaii", "Office of Hawaiian Affairs","At-Large"],
    ["Hawaii", "Office of Hawaiian Affairs","Maui"],
    ["Hawaii", "Office of Hawaiian Affairs","Oahu"],

    ["Idaho", "U.S House","CD-01"],
    ["Idaho", "U.S House","CD-02"],
    ["Idaho", "U.S Senate","Statewide"],
    ["Idaho", "Governor","Statewide"],
    ["Idaho", "Lieutenant Governor","Statewide"],
    ["Idaho", "Attorney General","Statewide"],
    ["Idaho", "Secretary of State","Statewide"],
    ["Idaho", "Controller","Statewide"],
    ["Idaho", "Superintendent of Public Instruction","Statewide"],
    ["Idaho", "Treasurer","Statewide"],

    ["Illinois", "U.S House","CD-01"],
    ["Illinois", "U.S House","CD-02"],
    ["Illinois", "U.S House","CD-03"],
    ["Illinois", "U.S House","CD-04"],
    ["Illinois", "U.S House","CD-05"],
    ["Illinois", "U.S House","CD-06"],
    ["Illinois", "U.S House","CD-07"],
    ["Illinois", "U.S House","CD-08"],
    ["Illinois", "U.S House","CD-09"],
    ["Illinois", "U.S House","CD-10"],
    ["Illinois", "U.S House","CD-11"],
    ["Illinois", "U.S House","CD-12"],
    ["Illinois", "U.S House","CD-13"],
    ["Illinois", "U.S House","CD-14"],
    ["Illinois", "U.S House","CD-15"],
    ["Illinois", "U.S House","CD-16"],
    ["Illinois", "U.S House","CD-17"],
    ["Illinois", "U.S Senate","Statewide"],
    ["Illinois", "Governor","Statewide"],
    ["Illinois", "Lieutenant Governor","Statewide"],
    ["Illinois", "Attorney General","Statewide"],
    ["Illinois", "Secretary of State","Statewide"],
    ["Illinois", "Comptroller","Statewide"],
    ["Illinois", "Treasurer","Statewide"],

    ["Indiana", "U.S House","CD-01"],
    ["Indiana", "U.S House","CD-02"],
    ["Indiana", "U.S House","CD-03"],
    ["Indiana", "U.S House","CD-04"],
    ["Indiana", "U.S House","CD-05"],
    ["Indiana", "U.S House","CD-06"],
    ["Indiana", "U.S House","CD-07"],
    ["Indiana", "U.S House","CD-08"],
    ["Indiana", "U.S House","CD-09"],
    ["Indiana", "U.S Senate","Statewide"],
    ["Indiana", "Governor","Statewide"],
    ["Indiana", "Lieutenant Governor","Statewide"],

    ["Iowa", "U.S House","CD-01"],
    ["Iowa", "U.S House","CD-02"],
    ["Iowa", "U.S House","CD-03"],
    ["Iowa", "U.S House","CD-04"],
    ["Iowa", "U.S Senate","Statewide"],
    ["Iowa", "Governor","Statewide"],
    ["Iowa", "Lieutenant Governor","Statewide"],
    ["Iowa", "Attorney General","Statewide"],
    ["Iowa", "Secretary of State","Statewide"],
    ["Iowa", "Treasurer","Statewide"],
    ["Iowa", "Secretary of Agriculture","Statewide"],
    ["Iowa", "Auditor","Statewide"],

    ["Kansas", "U.S House","CD-01"],
    ["Kansas", "U.S House","CD-02"],
    ["Kansas", "U.S House","CD-03"],
    ["Kansas", "U.S House","CD-04"],
    ["Kansas", "U.S Senate","Statewide"],
    ["Kansas", "Governor","Statewide"],
    ["Kansas", "Lieutenant Governor","Statewide"],
    ["Kansas", "Attorney General","Statewide"],
    ["Kansas", "Secretary of State","Statewide"],
    ["Kansas", "Insurance Commissioner","Statewide"],
    ["Kansas", "Treasurer","Statewide"],
    ["Kansas", "Board of Education","D1"],
    ["Kansas", "Board of Education","D3"],
    ["Kansas", "Board of Education","D5"],
    ["Kansas", "Board of Education","D7"],
    ["Kansas", "Board of Education","D9"],

    ["Kentucky", "U.S House","CD-01"],
    ["Kentucky", "U.S House","CD-02"],
    ["Kentucky", "U.S House","CD-03"],
    ["Kentucky", "U.S House","CD-04"],
    ["Kentucky", "U.S House","CD-05"],
    ["Kentucky", "U.S House","CD-06"],
    ["Kentucky", "U.S Senate","Statewide"],
    ["Kentucky", "Governor","Statewide"],
    ["Kentucky", "Lieutenant Governor","Statewide"],

    ["Louisiana", "U.S House","CD-01"],
    ["Louisiana", "U.S House","CD-02"],
    ["Louisiana", "U.S House","CD-03"],
    ["Louisiana", "U.S House","CD-04"],
    ["Louisiana", "U.S House","CD-05"],
    ["Louisiana", "U.S House","CD-06"],
    ["Louisiana", "U.S Senate","Statewide"],
    ["Louisiana", "Governor","Statewide"],
    ["Louisiana", "Lieutenant Governor","Statewide"],
    ["Louisiana", "Board of Elementary Education","D1"],
    ["Louisiana", "Public Service Commission","D1"],
    ["Louisiana", "Public Service Commission","D5"],

    ["Maine", "U.S House","CD-01"],
    ["Maine", "U.S House","CD-02"],
    ["Maine", "U.S Senate","Statewide"],
    ["Maine", "Governor","Statewide"],
    ["Maine", "Lieutenant Governor","Statewide"],

    ["Maryland", "U.S House","CD-01"],
    ["Maryland", "U.S House","CD-02"],
    ["Maryland", "U.S House","CD-03"],
    ["Maryland", "U.S House","CD-04"],
    ["Maryland", "U.S House","CD-05"],
    ["Maryland", "U.S House","CD-06"],
    ["Maryland", "U.S House","CD-07"],
    ["Maryland", "U.S Senate","Statewide"],
    ["Maryland", "Governor","Statewide"],
    ["Maryland", "Lieutenant Governor","Statewide"],
    ["Maryland", "Comptroller","Statewide"],

    ["Massachusetts", "U.S House","CD-01"],
    ["Massachusetts", "U.S House","CD-02"],
    ["Massachusetts", "U.S House","CD-03"],
    ["Massachusetts", "U.S House","CD-04"],
    ["Massachusetts", "U.S House","CD-05"],
    ["Massachusetts", "U.S House","CD-06"],
    ["Massachusetts", "U.S House","CD-07"],
    ["Massachusetts", "U.S House","CD-08"],
    ["Massachusetts", "U.S House","CD-09"],
    ["Massachusetts", "U.S Senate","Statewide"],
    ["Massachusetts", "Governor","Statewide"],
    ["Massachusetts", "Lieutenant Governor","Statewide"],
    ["Massachusetts", "Attorney General","Statewide"],
    ["Massachusetts", "Secretary of the Commonwealth","Statewide"],
    ["Massachusetts", "Treasurer and Receiver","Statewide"],
    ["Massachusetts", "Auditor","Statewide"],

    ["Michigan", "U.S House","CD-01"],
    ["Michigan", "U.S House","CD-02"],
    ["Michigan", "U.S House","CD-03"],
    ["Michigan", "U.S House","CD-04"],
    ["Michigan", "U.S House","CD-05"],
    ["Michigan", "U.S House","CD-06"],
    ["Michigan", "U.S House","CD-07"],
    ["Michigan", "U.S House","CD-08"],
    ["Michigan", "U.S House","CD-09"],
    ["Michigan", "U.S House","CD-10"],
    ["Michigan", "U.S House","CD-11"],
    ["Michigan", "U.S House","CD-12"],
    ["Michigan", "U.S House","CD-13"],
    ["Michigan", "U.S Senate","Statewide"],
    ["Michigan", "Governor","Statewide"],
    ["Michigan", "Lieutenant Governor","Statewide"],

    ["Minnesota", "U.S House","CD-01"],
    ["Minnesota", "U.S House","CD-02"],
    ["Minnesota", "U.S House","CD-03"],
    ["Minnesota", "U.S House","CD-04"],
    ["Minnesota", "U.S House","CD-05"],
    ["Minnesota", "U.S House","CD-06"],
    ["Minnesota", "U.S House","CD-07"],
    ["Minnesota", "U.S House","CD-08"],
    ["Minnesota", "U.S Senate","Statewide"],
    ["Minnesota", "Governor","Statewide"],
    ["Minnesota", "Lieutenant Governor","Statewide"],

    ["Mississippi", "U.S House","CD-01"],
    ["Mississippi", "U.S House","CD-02"],
    ["Mississippi", "U.S House","CD-03"],
    ["Mississippi", "U.S House","CD-04"],
    ["Mississippi", "U.S Senate","Statewide"],
    ["Mississippi", "Governor","Statewide"],
    ["Mississippi", "Lieutenant Governor","Statewide"],

    ["Missouri", "U.S House","CD-01"],
    ["Missouri", "U.S House","CD-02"],
    ["Missouri", "U.S House","CD-03"],
    ["Missouri", "U.S House","CD-04"],
    ["Missouri", "U.S House","CD-05"],
    ["Missouri", "U.S House","CD-06"],
    ["Missouri", "U.S House","CD-07"],
    ["Missouri", "U.S House","CD-08"],
    ["Missouri", "U.S Senate","Statewide"],
    ["Missouri", "Governor","Statewide"],
    ["Missouri", "Lieutenant Governor","Statewide"],
    ["Missouri", "Auditor","Statewide"],

];
/*as a note, the creator I booted this from says this is the difficult way to do this. if I would like to update it with more dropdowns such as 4 or 5, it is 
possible to use classes instead. for now (6/25/26) I got this working and am just going to roll with it. sorry to anyone looking in the future */

function makeDropdown(data,filtersAsArray,targetElement){
    const filteredArray = filterArray(data,filtersAsArray);
    const uniqueList = getUniqueValues(filteredArray, filtersAsArray.length);
    populateDropdown(targetElement, uniqueList);
}

function applyDropdown(){
    const selectState = document.getElementById("State").value;
    const selectOffice = document.getElementById("Office");
    makeDropdown(myData,[selectState],selectOffice);
    applyDropdown2();
}

function applyDropdown2(){
    const selectState = document.getElementById("State").value;
    const selectOffice = document.getElementById("Office").value;
    const selectJurisdiction = document.getElementById("Jurisdiction");
    makeDropdown(myData,[selectState, selectOffice],selectJurisdiction);
}

function onLoad(){
    populateFirstLevelDropdown();
    applyDropdown();
}

function getUniqueValues(data,index){
    const uniqueOptions = new Set();
    data.forEach(r => uniqueOptions.add(r[index]));
    return [...uniqueOptions];
}

function populateFirstLevelDropdown(){
    const uniqueList = getUniqueValues(myData,0);
    const el = document.getElementById("State");
    populateDropdown(el, uniqueList);
}

function populateDropdown(el, listAsArray){
    el.innerHTML = "";
    listAsArray.forEach(item => {
        const option = document.createElement("option");
        option.textContent = item;
        el.appendChild(option);
});
}

function filterArray(data,filtersAsArray){
    return data.filter(r => filtersAsArray.every((item,i) => item === r[i]));
}


document.getElementById("State").addEventListener("change",applyDropdown);
document.getElementById("Office").addEventListener("change",applyDropdown2);
document.addEventListener("DOMContentLoaded", onLoad);



/*var dd = new DropDown(myData).eazyDropDown(["State", "Office","District"]); */