var myData = [ /*the list of races here pulls from the 2026 All State
    Mastersheet, will add more eventually but am going off of this
    so I don't have to put in a billion races */
    ["-- State --", "-- Office --", "-- Jurisdiction --"],
    ["Alabama", "U.S House","CD-01"],
    ["Alabama", "U.S House","CD-02"],
    ["Alabama", "U.S House","CD-03"],
    ["Alabama", "U.S House","CD-04"],
    ["Alabama", "U.S House","CD-05"],
    ["Alabama", "U.S House","CD-06"],
    ["Alabama", "U.S House","CD-07"],
    ["Alabama", "U.S Senate","Statewide"],
    ["Alabama", "Governor","Statewide"],
    ["Alabama", "Lieutenant Governor","Statewide"],
    ["Alabama", "Attorney General","Statewide"],
    ["Alabama", "Secretary of State","Statewide"],
    ["Alabama", "Treasurer","Statewide"],
    ["Alabama", "Auditor","Statewide"],
    ["Alabama", "Commissioner of Agriculture","Statewide"],
    ["Alabama", "Supreme Court","S1"],
    ["Alabama", "Supreme Court","S2"],
    ["Alabama", "Supreme Court","S8"],
    ["Alabama", "Court of Civil Appeals","S4"],
    ["Alabama", "Court of Civil Appeals","S5"],
    ["Alabama", "Court of Criminal Appeals","S4"],
    ["Alabama", "Court of Criminal Appeals","S5"],
    ["Alabama", "Board of Education","D2"],
    ["Alabama", "Board of Education","D4"],
    ["Alabama", "Board of Education","D6"],
    ["Alabama", "Board of Education","D8"],
    ["Alabama", "Public Service Commission","P1"],
    ["Alabama", "Public Service Commission","P2"],

    ["Alaska", "U.S House","At-Large"],
    ["Alaska", "U.S Senate","Statewide"],
    ["Alaska", "Governor","Statewide"],

    ["Arizona", "U.S House","CD-01"],
    ["Arizona", "U.S House","CD-02"],
    ["Arizona", "U.S House","CD-03"],
    ["Arizona", "U.S House","CD-04"],
    ["Arizona", "U.S House","CD-05"],
    ["Arizona", "U.S House","CD-06"],
    ["Arizona", "U.S House","CD-07"],
    ["Arizona", "U.S House","CD-08"],
    ["Arizona", "U.S House","CD-09"],
    ["Arizona", "U.S Senate","Statewide"],
    ["Arizona", "Governor","Statewide"],
    ["Arizona", "Lieutenant Governor","Statewide"],
    ["Arizona", "Attorney General","Statewide"],
    ["Arizona", "Secretary of State","Statewide"],

    ["Arkansas", "U.S House","CD-01"],
    ["Arkansas", "U.S House","CD-02"],
    ["Arkansas", "U.S House","CD-03"],
    ["Arkansas", "U.S House","CD-04"],
    ["Arkansas", "U.S Senate","Statewide"],
    ["Arkansas", "Governor","Statewide"],
    ["Arkansas", "Lieutenant Governor","Statewide"],
    ["Arkansas", "Attorney General","Statewide"],
    ["Arkansas", "Secretary of State","Statewide"],
    ["Arkansas", "Auditor","Statewide"],
    ["Arkansas", "Commissioner of State Lands","Statewide"],
    ["Arkansas", "Treasurer","Statewide"],
    
    ["California", "U.S House","CD-01"],
    ["California", "U.S House","CD-02"],
    ["California", "U.S House","CD-03"],
    ["California", "U.S House","CD-04"],
    ["California", "U.S House","CD-05"],
    ["California", "U.S House","CD-06"],
    ["California", "U.S House","CD-07"],
    ["California", "U.S House","CD-08"],
    ["California", "U.S House","CD-09"],
    ["California", "U.S House","CD-10"],
    ["California", "U.S House","CD-11"],
    ["California", "U.S House","CD-12"],
    ["California", "U.S House","CD-13"],
    ["California", "U.S House","CD-14"],
    ["California", "U.S House","CD-15"],
    ["California", "U.S House","CD-16"],
    ["California", "U.S House","CD-17"],
    ["California", "U.S House","CD-18"],
    ["California", "U.S House","CD-19"],
    ["California", "U.S House","CD-20"],
    ["California", "U.S House","CD-21"],
    ["California", "U.S House","CD-22"],
    ["California", "U.S House","CD-23"],
    ["California", "U.S House","CD-24"],
    ["California", "U.S House","CD-25"],
    ["California", "U.S House","CD-26"],
    ["California", "U.S House","CD-27"],
    ["California", "U.S House","CD-28"],
    ["California", "U.S House","CD-29"],
    ["California", "U.S House","CD-30"],
    ["California", "U.S House","CD-31"],
    ["California", "U.S House","CD-32"],
    ["California", "U.S House","CD-33"],
    ["California", "U.S House","CD-34"],
    ["California", "U.S House","CD-35"],
    ["California", "U.S House","CD-36"],
    ["California", "U.S House","CD-37"],
    ["California", "U.S House","CD-38"],
    ["California", "U.S House","CD-39"],
    ["California", "U.S House","CD-40"],
    ["California", "U.S House","CD-41"],
    ["California", "U.S House","CD-42"],
    ["California", "U.S House","CD-43"],
    ["California", "U.S House","CD-44"],
    ["California", "U.S House","CD-45"],
    ["California", "U.S House","CD-46"],
    ["California", "U.S House","CD-47"],
    ["California", "U.S House","CD-48"],
    ["California", "U.S House","CD-49"],
    ["California", "U.S House","CD-50"],
    ["California", "U.S House","CD-51"],
    ["California", "U.S House","CD-52"],
    ["California", "U.S Senate","Statewide"],
    ["California", "Governor","Statewide"],
    ["California", "Lieutenant Governor","Statewide"],
    ["California", "Secretary of State","Statewide"],
    ["California", "Attorney General","Statewide"],
    ["California", "Treasurer","Statewide"],
    ["California", "State Controller","Statewide"],
    ["California", "Insurance Commissioner","Statewide"],
    ["California", "Board of Equalization","Statewide"],
    
    ["Colorado", "U.S House","CD-01"],
    ["Colorado", "U.S House","CD-02"],
    ["Colorado", "U.S House","CD-03"],
    ["Colorado", "U.S House","CD-04"],
    ["Colorado", "U.S House","CD-05"],
    ["Colorado", "U.S House","CD-06"],
    ["Colorado", "U.S House","CD-07"],
    ["Colorado", "U.S House","CD-08"],
    ["Colorado", "U.S Senate","Statewide"],
    ["Colorado", "Governor","Statewide"],
    ["Colorado", "Lieutenant Governor","Statewide"],
    ["Colorado", "Secretary of State","Statewide"],
    ["Colorado", "Attorney General","Statewide"],
    ["Colorado", "Treasurer","Statewide"],
    ["Colorado", "State Board of Education","D1"],
    ["Colorado", "State Board of Education","D3"],
    ["Colorado", "State Board of Education","D7"],
    ["Colorado", "State Board of Regents","D2"],
    ["Colorado", "State Board of Regents","D6"],
    ["Colorado", "State Board of Regents","D7"],

    ["Connecticut", "U.S House","CD-01"],
    ["Connecticut", "U.S House","CD-02"],
    ["Connecticut", "U.S House","CD-03"],
    ["Connecticut", "U.S House","CD-04"],
    ["Connecticut", "U.S House","CD-05"],
    ["Connecticut", "U.S Senate","Statewide"],
    ["Connecticut", "Governor","Statewide"],
    ["Connecticut", "Lieutenant Governor","Statewide"],
    ["Connecticut", "Attorney General","Statewide"],
    ["Connecticut", "Secretary of State","Statewide"],
    ["Connecticut", "Comptroller","Statewide"],
    ["Connecticut", "Treasurer","Statewide"],

    ["Delaware", "U.S House","At-Large"],
    ["Delaware", "U.S Senate","Statewide"],
    ["Delaware", "Governor","Statewide"],
    ["Delaware", "Lieutenant Governor","Statewide"],
    ["Delaware", "Auditor","Statewide"],
    ["Delaware", "Treasurer","Statewide"],

    ["Florida", "U.S House","CD-01"],
    ["Florida", "U.S House","CD-02"],
    ["Florida", "U.S House","CD-03"],
    ["Florida", "U.S House","CD-04"],
    ["Florida", "U.S House","CD-05"],
    ["Florida", "U.S House","CD-06"],
    ["Florida", "U.S House","CD-07"],
    ["Florida", "U.S House","CD-08"],
    ["Florida", "U.S House","CD-09"],
    ["Florida", "U.S House","CD-10"],
    ["Florida", "U.S House","CD-11"],
    ["Florida", "U.S House","CD-12"],
    ["Florida", "U.S House","CD-13"],
    ["Florida", "U.S House","CD-14"],
    ["Florida", "U.S House","CD-15"],
    ["Florida", "U.S House","CD-16"],
    ["Florida", "U.S House","CD-17"],
    ["Florida", "U.S House","CD-18"],
    ["Florida", "U.S House","CD-19"],
    ["Florida", "U.S House","CD-20"],
    ["Florida", "U.S House","CD-21"],
    ["Florida", "U.S House","CD-22"],
    ["Florida", "U.S House","CD-23"],
    ["Florida", "U.S House","CD-24"],
    ["Florida", "U.S House","CD-25"],
    ["Florida", "U.S House","CD-26"],
    ["Florida", "U.S House","CD-27"],
    ["Florida", "U.S House","CD-28"],
    ["Florida", "U.S Senate","Statewide"],
    ["Florida", "Governor","Statewide"],
    ["Florida", "Lieutenant Governor","Statewide"],
    ["Florida", "Attorney General","Statewide"],
    ["Florida", "Agriculture Commissioner","Statewide"],
    ["Florida", "Treasurer","Statewide"],
    ["Florida", "Supreme Court","Statewide"],

    ["Georgia", "U.S House","CD-01"],
    ["Georgia", "U.S House","CD-02"],
    ["Georgia", "U.S House","CD-03"],
    ["Georgia", "U.S House","CD-04"],
    ["Georgia", "U.S House","CD-05"],
    ["Georgia", "U.S House","CD-06"],
    ["Georgia", "U.S House","CD-07"],
    ["Georgia", "U.S House","CD-08"],
    ["Georgia", "U.S House","CD-09"],
    ["Georgia", "U.S House","CD-10"],
    ["Georgia", "U.S House","CD-11"],
    ["Georgia", "U.S House","CD-12"],
    ["Georgia", "U.S House","CD-13"],
    ["Georgia", "U.S House","CD-14"],
    ["Georgia", "U.S Senate","Statewide"],
    ["Georgia", "Governor","Statewide"],
    ["Georgia", "Lieutenant Governor","Statewide"],
    ["Georgia", "Attorney General","Statewide"],
    ["Georgia", "Secretary of State","Statewide"],
    ["Georgia", "Agriculture Commissioner","Statewide"],
    ["Georgia", "Insurance and Fire Safety Commissioner","Statewide"],
    ["Georgia", "Labor Commissioner","Statewide"],
    ["Georgia", "Superintendent of Pubilic Instruction","Statewide"],
    ["Georgia", "Public Service Commission","D3"],
    ["Georgia", "Public Service Commission","D5"],

    ["Hawaii", "U.S House","CD-01"],
    ["Hawaii", "U.S House","CD-02"],
    ["Hawaii", "U.S Senate","Statewide"],
    ["Hawaii", "Governor","Statewide"],
    ["Hawaii", "Lieutenant Governor","Statewide"],
    ["Hawaii", "Office of Hawaiian Affairs","At-Large"],
    ["Hawaii", "Office of Hawaiian Affairs","Maui"],
    ["Hawaii", "Office of Hawaiian Affairs","Oahu"],

    ["Idaho", "U.S House","CD-01"],
    ["Idaho", "U.S House","CD-02"],
    ["Idaho", "U.S Senate","Statewide"],
    ["Idaho", "Governor","Statewide"],
    ["Idaho", "Lieutenant Governor","Statewide"],
    ["Idaho", "Attorney General","Statewide"],
    ["Idaho", "Secretary of State","Statewide"],
    ["Idaho", "Controller","Statewide"],
    ["Idaho", "Superintendent of Public Instruction","Statewide"],
    ["Idaho", "Treasurer","Statewide"],

    ["Illinois", "U.S House","CD-01"],
    ["Illinois", "U.S House","CD-02"],
    ["Illinois", "U.S House","CD-03"],
    ["Illinois", "U.S House","CD-04"],
    ["Illinois", "U.S House","CD-05"],
    ["Illinois", "U.S House","CD-06"],
    ["Illinois", "U.S House","CD-07"],
    ["Illinois", "U.S House","CD-08"],
    ["Illinois", "U.S House","CD-09"],
    ["Illinois", "U.S House","CD-10"],
    ["Illinois", "U.S House","CD-11"],
    ["Illinois", "U.S House","CD-12"],
    ["Illinois", "U.S House","CD-13"],
    ["Illinois", "U.S House","CD-14"],
    ["Illinois", "U.S House","CD-15"],
    ["Illinois", "U.S House","CD-16"],
    ["Illinois", "U.S House","CD-17"],
    ["Illinois", "U.S Senate","Statewide"],
    ["Illinois", "Governor","Statewide"],
    ["Illinois", "Lieutenant Governor","Statewide"],
    ["Illinois", "Attorney General","Statewide"],
    ["Illinois", "Secretary of State","Statewide"],
    ["Illinois", "Comptroller","Statewide"],
    ["Illinois", "Treasurer","Statewide"],

    ["Indiana", "U.S House","CD-01"],
    ["Indiana", "U.S House","CD-02"],
    ["Indiana", "U.S House","CD-03"],
    ["Indiana", "U.S House","CD-04"],
    ["Indiana", "U.S House","CD-05"],
    ["Indiana", "U.S House","CD-06"],
    ["Indiana", "U.S House","CD-07"],
    ["Indiana", "U.S House","CD-08"],
    ["Indiana", "U.S House","CD-09"],
    ["Indiana", "U.S Senate","Statewide"],
    ["Indiana", "Governor","Statewide"],
    ["Indiana", "Lieutenant Governor","Statewide"],

    ["Iowa", "U.S House","CD-01"],
    ["Iowa", "U.S House","CD-02"],
    ["Iowa", "U.S House","CD-03"],
    ["Iowa", "U.S House","CD-04"],
    ["Iowa", "U.S Senate","Statewide"],
    ["Iowa", "Governor","Statewide"],
    ["Iowa", "Lieutenant Governor","Statewide"],
    ["Iowa", "Attorney General","Statewide"],
    ["Iowa", "Secretary of State","Statewide"],
    ["Iowa", "Treasurer","Statewide"],
    ["Iowa", "Secretary of Agriculture","Statewide"],
    ["Iowa", "Auditor","Statewide"],

    ["Kansas", "U.S House","CD-01"],
    ["Kansas", "U.S House","CD-02"],
    ["Kansas", "U.S House","CD-03"],
    ["Kansas", "U.S House","CD-04"],
    ["Kansas", "U.S Senate","Statewide"],
    ["Kansas", "Governor","Statewide"],
    ["Kansas", "Lieutenant Governor","Statewide"],
    ["Kansas", "Attorney General","Statewide"],
    ["Kansas", "Secretary of State","Statewide"],
    ["Kansas", "Insurance Commissioner","Statewide"],
    ["Kansas", "Treasurer","Statewide"],
    ["Kansas", "Board of Education","D1"],
    ["Kansas", "Board of Education","D3"],
    ["Kansas", "Board of Education","D5"],
    ["Kansas", "Board of Education","D7"],
    ["Kansas", "Board of Education","D9"],

    ["Kentucky", "U.S House","CD-01"],
    ["Kentucky", "U.S House","CD-02"],
    ["Kentucky", "U.S House","CD-03"],
    ["Kentucky", "U.S House","CD-04"],
    ["Kentucky", "U.S House","CD-05"],
    ["Kentucky", "U.S House","CD-06"],
    ["Kentucky", "U.S Senate","Statewide"],
    ["Kentucky", "Governor","Statewide"],
    ["Kentucky", "Lieutenant Governor","Statewide"],

    ["Louisiana", "U.S House","CD-01"],
    ["Louisiana", "U.S House","CD-02"],
    ["Louisiana", "U.S House","CD-03"],
    ["Louisiana", "U.S House","CD-04"],
    ["Louisiana", "U.S House","CD-05"],
    ["Louisiana", "U.S House","CD-06"],
    ["Louisiana", "U.S Senate","Statewide"],
    ["Louisiana", "Governor","Statewide"],
    ["Louisiana", "Lieutenant Governor","Statewide"],
    ["Louisiana", "Board of Elementary Education","D1"],
    ["Louisiana", "Public Service Commission","D1"],
    ["Louisiana", "Public Service Commission","D5"],

    ["Maine", "U.S House","CD-01"],
    ["Maine", "U.S House","CD-02"],
    ["Maine", "U.S Senate","Statewide"],
    ["Maine", "Governor","Statewide"],
    ["Maine", "Lieutenant Governor","Statewide"],

    ["Maryland", "U.S House","CD-01"],
    ["Maryland", "U.S House","CD-02"],
    ["Maryland", "U.S House","CD-03"],
    ["Maryland", "U.S House","CD-04"],
    ["Maryland", "U.S House","CD-05"],
    ["Maryland", "U.S House","CD-06"],
    ["Maryland", "U.S House","CD-07"],
    ["Maryland", "U.S Senate","Statewide"],
    ["Maryland", "Governor","Statewide"],
    ["Maryland", "Lieutenant Governor","Statewide"],
    ["Maryland", "Comptroller","Statewide"],

    ["Massachusetts", "U.S House","CD-01"],
    ["Massachusetts", "U.S House","CD-02"],
    ["Massachusetts", "U.S House","CD-03"],
    ["Massachusetts", "U.S House","CD-04"],
    ["Massachusetts", "U.S House","CD-05"],
    ["Massachusetts", "U.S House","CD-06"],
    ["Massachusetts", "U.S House","CD-07"],
    ["Massachusetts", "U.S House","CD-08"],
    ["Massachusetts", "U.S House","CD-09"],
    ["Massachusetts", "U.S Senate","Statewide"],
    ["Massachusetts", "Governor","Statewide"],
    ["Massachusetts", "Lieutenant Governor","Statewide"],
    ["Massachusetts", "Attorney General","Statewide"],
    ["Massachusetts", "Secretary of the Commonwealth","Statewide"],
    ["Massachusetts", "Treasurer and Receiver","Statewide"],
    ["Massachusetts", "Auditor","Statewide"],

    ["Michigan", "U.S House","CD-01"],
    ["Michigan", "U.S House","CD-02"],
    ["Michigan", "U.S House","CD-03"],
    ["Michigan", "U.S House","CD-04"],
    ["Michigan", "U.S House","CD-05"],
    ["Michigan", "U.S House","CD-06"],
    ["Michigan", "U.S House","CD-07"],
    ["Michigan", "U.S House","CD-08"],
    ["Michigan", "U.S House","CD-09"],
    ["Michigan", "U.S House","CD-10"],
    ["Michigan", "U.S House","CD-11"],
    ["Michigan", "U.S House","CD-12"],
    ["Michigan", "U.S House","CD-13"],
    ["Michigan", "U.S Senate","Statewide"],
    ["Michigan", "Governor","Statewide"],
    ["Michigan", "Lieutenant Governor","Statewide"],

    ["Minnesota", "U.S House","CD-01"],
    ["Minnesota", "U.S House","CD-02"],
    ["Minnesota", "U.S House","CD-03"],
    ["Minnesota", "U.S House","CD-04"],
    ["Minnesota", "U.S House","CD-05"],
    ["Minnesota", "U.S House","CD-06"],
    ["Minnesota", "U.S House","CD-07"],
    ["Minnesota", "U.S House","CD-08"],
    ["Minnesota", "U.S Senate","Statewide"],
    ["Minnesota", "Governor","Statewide"],
    ["Minnesota", "Lieutenant Governor","Statewide"],

    ["Mississippi", "U.S House","CD-01"],
    ["Mississippi", "U.S House","CD-02"],
    ["Mississippi", "U.S House","CD-03"],
    ["Mississippi", "U.S House","CD-04"],
    ["Mississippi", "U.S Senate","Statewide"],
    ["Mississippi", "Governor","Statewide"],
    ["Mississippi", "Lieutenant Governor","Statewide"],

    ["Missouri", "U.S House","CD-01"],
    ["Missouri", "U.S House","CD-02"],
    ["Missouri", "U.S House","CD-03"],
    ["Missouri", "U.S House","CD-04"],
    ["Missouri", "U.S House","CD-05"],
    ["Missouri", "U.S House","CD-06"],
    ["Missouri", "U.S House","CD-07"],
    ["Missouri", "U.S House","CD-08"],
    ["Missouri", "U.S Senate","Statewide"],
    ["Missouri", "Governor","Statewide"],
    ["Missouri", "Lieutenant Governor","Statewide"],
    ["Missouri", "Auditor","Statewide"],

    ["Montana", "U.S House","CD-01"],
    ["Montana", "U.S House","CD-02"],
    ["Montana", "U.S Senate","Statewide"],
    ["Montana", "Governor","Statewide"],
    ["Montana", "Lieutenant Governor","Statewide"],
    ["Montana", "Public Service Commission","S1"],
    ["Montana", "Public Service Commission","S5"],
    ["Montana", "Supreme Court","Statewide"],

    ["Nebraska", "U.S House","CD-01"],
    ["Nebraska", "U.S House","CD-02"],
    ["Nebraska", "U.S House","CD-03"],
    ["Nebraska", "U.S Senate","Statewide"],
    ["Nebraska", "Governor","Statewide"],
    ["Nebraska", "Lieutenant Governor","Statewide"],
    ["Nebraska", "Attorney General","Statewide"],
    ["Nebraska", "Secretary of State","Statewide"],
    ["Nebraska", "Auditor","Statewide"],

    ["Nevada", "U.S House","CD-01"],
    ["Nevada", "U.S House","CD-02"],
    ["Nevada", "U.S House","CD-03"],
    ["Nevada", "U.S House","CD-04"],
    ["Nevada", "U.S Senate","Statewide"],
    ["Nevada", "Governor","Statewide"],
    ["Nevada", "Lieutenant Governor","Statewide"],
    ["Nevada", "Attorney General","Statewide"],
    ["Nevada", "Secretary of State","Statewide"],
    ["Nevada", "Controller","Statewide"],
    ["Nevada", "Treasurer","Statewide"],
    ["Nevada", "Board of Regents","D2"],
    ["Nevada", "Board of Regents","D3"],
    ["Nevada", "Board of Regents","D5"],
    ["Nevada", "Board of Regents","D8"],
    ["Nevada", "Board of Regents","D10"],

    ["New Hampshire", "U.S House","CD-01"],
    ["New Hampshire", "U.S House","CD-02"],
    ["New Hampshire", "U.S Senate","Statewide"],
    ["New Hampshire", "Governor","Statewide"],
    ["New Hampshire", "Lieutenant Governor","Statewide"],
    ["New Hampshire", "Executive Council","S1"],
    ["New Hampshire", "Executive Council","S2"],
    ["New Hampshire", "Executive Council","S3"],
    ["New Hampshire", "Executive Council","S4"],
    ["New Hampshire", "Executive Council","S5"],

    ["New Jersey", "U.S House","CD-01"],
    ["New Jersey", "U.S House","CD-02"],
    ["New Jersey", "U.S House","CD-03"],
    ["New Jersey", "U.S House","CD-04"],
    ["New Jersey", "U.S House","CD-05"],
    ["New Jersey", "U.S House","CD-06"],
    ["New Jersey", "U.S House","CD-07"],
    ["New Jersey", "U.S House","CD-08"],
    ["New Jersey", "U.S House","CD-09"],
    ["New Jersey", "U.S House","CD-10"],
    ["New Jersey", "U.S House","CD-11"],
    ["New Jersey", "U.S House","CD-12"],
    ["New Jersey", "U.S Senate","Statewide"],
    ["New Jersey", "Governor","Statewide"],
    ["New Jersey", "Lieutenant Governor","Statewide"],

    ["New Mexico", "U.S House","CD-01"],
    ["New Mexico", "U.S House","CD-02"],
    ["New Mexico", "U.S House","CD-03"],
    ["New Mexico", "U.S Senate","Statewide"],
    ["New Mexico", "Governor","Statewide"],
    ["New Mexico", "Lieutenant Governor","Statewide"],
    ["New Mexico", "Attorney General","Statewide"],
    ["New Mexico", "Secretary of State","Statewide"],
    ["New Mexico", "Auditor","Statewide"],
    ["New Mexico", "Commissioner of Public Lands","Statewide"],
    ["New Mexico", "Treasurer","Statewide"],
    ["New Mexico", "Public Education Commission","S2"],
    ["New Mexico", "Public Education Commission","S3"],
    ["New Mexico", "Public Education Commission","S5"],
    ["New Mexico", "Public Education Commission","S6"],
    ["New Mexico", "Public Education Commission","S7"],

    ["New York", "U.S House","CD-01"],
    ["New York", "U.S House","CD-02"],
    ["New York", "U.S House","CD-03"],
    ["New York", "U.S House","CD-04"],
    ["New York", "U.S House","CD-05"],
    ["New York", "U.S House","CD-06"],
    ["New York", "U.S House","CD-07"],
    ["New York", "U.S House","CD-08"],
    ["New York", "U.S House","CD-09"],
    ["New York", "U.S House","CD-10"],
    ["New York", "U.S House","CD-11"],
    ["New York", "U.S House","CD-12"],
    ["New York", "U.S House","CD-13"],
    ["New York", "U.S House","CD-14"],
    ["New York", "U.S House","CD-15"],
    ["New York", "U.S House","CD-16"],
    ["New York", "U.S House","CD-17"],
    ["New York", "U.S House","CD-18"],
    ["New York", "U.S House","CD-19"],
    ["New York", "U.S House","CD-20"],
    ["New York", "U.S House","CD-21"],
    ["New York", "U.S House","CD-22"],
    ["New York", "U.S House","CD-23"],
    ["New York", "U.S House","CD-24"],
    ["New York", "U.S House","CD-25"],
    ["New York", "U.S House","CD-26"],
    ["New York", "U.S Senate","Statewide"],
    ["New York", "Governor","Statewide"],
    ["New York", "Lieutenant Governor","Statewide"],
    ["New York", "Attorney General","Statewide"], 
    ["New York", "Comptroller","Statewide"], 
    
    ["North Carolina", "U.S House","CD-01"],
    ["North Carolina", "U.S House","CD-02"],
    ["North Carolina", "U.S House","CD-03"],
    ["North Carolina", "U.S House","CD-04"],
    ["North Carolina", "U.S House","CD-05"],
    ["North Carolina", "U.S House","CD-06"],
    ["North Carolina", "U.S House","CD-07"],
    ["North Carolina", "U.S House","CD-08"],
    ["North Carolina", "U.S House","CD-09"],
    ["North Carolina", "U.S House","CD-10"],
    ["North Carolina", "U.S House","CD-11"],
    ["North Carolina", "U.S House","CD-12"],
    ["North Carolina", "U.S House","CD-13"],
    ["North Carolina", "U.S House","CD-14"],
    ["North Carolina", "U.S Senate","Statewide"],
    ["North Carolina", "Governor","Statewide"],
    ["North Carolina", "Lieutenant Governor","Statewide"],
    ["North Carolina", "Supreme Court","Statewide"],
    ["North Carolina", "Appellate Court","S1"],
    ["North Carolina", "Appellate Court","S2"],
    ["North Carolina", "Appellate Court","S3"],

    ["North Dakota", "U.S House","CD-01"],
    ["North Dakota", "U.S Senate","Statewide"],
    ["North Dakota", "Governor","Statewide"],
    ["North Dakota", "Lieutenant Governor","Statewide"],
    ["North Dakota", "Attorney General","Statewide"],
    ["North Dakota", "Secretary of State","Statewide"],
    ["North Dakota", "Agriculture Commissioner","Statewide"],
    ["North Dakota", "Superintendent of Public Instruction","Statewide"],
    ["North Dakota", "Tax Commissioner","Statewide"],
    ["North Dakota", "Public Service Commission","Statewide"],

    ["Ohio", "U.S House","CD-01"],
    ["Ohio", "U.S House","CD-02"],
    ["Ohio", "U.S House","CD-03"],
    ["Ohio", "U.S House","CD-04"],
    ["Ohio", "U.S House","CD-05"],
    ["Ohio", "U.S House","CD-06"],
    ["Ohio", "U.S House","CD-07"],
    ["Ohio", "U.S House","CD-08"],
    ["Ohio", "U.S House","CD-09"],
    ["Ohio", "U.S House","CD-10"],
    ["Ohio", "U.S House","CD-11"],
    ["Ohio", "U.S House","CD-12"],
    ["Ohio", "U.S House","CD-13"],
    ["Ohio", "U.S House","CD-14"],
    ["Ohio", "U.S House","CD-15"],
    ["Ohio", "U.S Senate","Statewide"],
    ["Ohio", "Governor","Statewide"],
    ["Ohio", "Lieutenant Governor","Statewide"],
    ["Ohio", "Attorney General","Statewide"],
    ["Ohio", "Secretary of State","Statewide"],
    ["Ohio", "Auditor","Statewide"],
    ["Ohio", "Treasurer","Statewide"],

    ["Oklahoma", "U.S House","CD-01"],
    ["Oklahoma", "U.S House","CD-02"],
    ["Oklahoma", "U.S House","CD-03"],
    ["Oklahoma", "U.S House","CD-04"],
    ["Oklahoma", "U.S House","CD-05"],
    ["Oklahoma", "U.S House","CD-06"],
    ["Oklahoma", "U.S Senate","Statewide"],
    ["Oklahoma", "Governor","Statewide"],
    ["Oklahoma", "Lieutenant Governor","Statewide"],
    ["Oklahoma", "Attorney General","Statewide"],
    ["Oklahoma", "Auditor","Statewide"],
    ["Oklahoma", "Treasurer","Statewide"],
    ["Oklahoma", "Insurance Commissioner","Statewide"],
    ["Oklahoma", "Labor Commissioner","Statewide"],
    ["Oklahoma", "Superintendent of Public Instruction","Statewide"],
    ["Oklahoma", "Corporation Commission","Statewide"],

    ["Oregon", "U.S House","CD-01"],
    ["Oregon", "U.S House","CD-02"],
    ["Oregon", "U.S House","CD-03"],
    ["Oregon", "U.S House","CD-04"],
    ["Oregon", "U.S House","CD-05"],
    ["Oregon", "U.S House","CD-06"],
    ["Oregon", "U.S House","CD-07"],
    ["Oregon", "U.S House","CD-08"],
    ["Oregon", "U.S Senate","Statewide"],
    ["Oregon", "Governor","Statewide"],
    ["Oregon", "Lieutenant Governor","Statewide"],
    ["Oregon", "Commissioner of Labor and Industries","Statewide"],

    ["Pennsylvania", "U.S House","CD-01"],
    ["Pennsylvania", "U.S House","CD-02"],
    ["Pennsylvania", "U.S House","CD-03"],
    ["Pennsylvania", "U.S House","CD-04"],
    ["Pennsylvania", "U.S House","CD-05"],
    ["Pennsylvania", "U.S House","CD-06"],
    ["Pennsylvania", "U.S House","CD-07"],
    ["Pennsylvania", "U.S House","CD-08"],
    ["Pennsylvania", "U.S House","CD-09"],
    ["Pennsylvania", "U.S House","CD-10"],
    ["Pennsylvania", "U.S House","CD-11"],
    ["Pennsylvania", "U.S House","CD-12"],
    ["Pennsylvania", "U.S House","CD-13"],
    ["Pennsylvania", "U.S House","CD-14"],
    ["Pennsylvania", "U.S House","CD-15"],
    ["Pennsylvania", "U.S House","CD-16"],
    ["Pennsylvania", "U.S House","CD-17"],
    ["Pennsylvania", "U.S Senate","Statewide"],
    ["Pennsylvania", "Governor","Statewide"],
    ["Pennsylvania", "Lieutenant Governor","Statewide"],

    ["Rhode Island", "U.S House","CD-01"],
    ["Rhode Island", "U.S House","CD-02"],
    ["Rhode Island", "U.S Senate","Statewide"],
    ["Rhode Island", "Governor","Statewide"],
    ["Rhode Island", "Lieutenant Governor","Statewide"],
    ["Rhode Island", "Attorney General","Statewide"],
    ["Rhode Island", "Secretary of State","Statewide"],
    ["Rhode Island", "Auditor","Statewide"],
    ["Rhode Island", "Treasurer","Statewide"],

    ["South Carolina", "U.S House","CD-01"],
    ["South Carolina", "U.S House","CD-02"],
    ["South Carolina", "U.S House","CD-03"],
    ["South Carolina", "U.S House","CD-04"],
    ["South Carolina", "U.S House","CD-05"],
    ["South Carolina", "U.S House","CD-06"],
    ["South Carolina", "U.S House","CD-07"],
    ["South Carolina", "U.S Senate","Statewide"],
    ["South Carolina", "Governor","Statewide"],
    ["South Carolina", "Lieutenant Governor","Statewide"],
    ["South Carolina", "Attorney General","Statewide"],
    ["South Carolina", "Secretary of State","Statewide"],
    ["South Carolina", "Treasurer","Statewide"],
    ["South Carolina", "Comptroller","Statewide"],
    ["South Carolina", "Superintendent of Education","Statewide"],
    ["South Carolina", "Commissioner of Agriculture","Statewide"],

    ["South Dakota", "U.S House","At-Large"],
    ["South Dakota", "U.S Senate","Statewide"],
    ["South Dakota", "Governor","Statewide"],
    ["South Dakota", "Lieutenant Governor","Statewide"],
    ["South Dakota", "Attorney General","Statewide"],
    ["South Dakota", "Secretary of State","Statewide"],
    ["South Dakota", "Auditor","Statewide"],
    ["South Dakota", "Commissioner of School and Public Lands","Statewide"],
    ["South Dakota", "Treasurer","Statewide"],
    ["South Dakota", "Public Utilities Commission","Statewide"],
    ["South Dakota", "Supreme Court","Statewide"],

    ["Tennessee", "U.S House","CD-01"],
    ["Tennessee", "U.S House","CD-02"],
    ["Tennessee", "U.S House","CD-03"],
    ["Tennessee", "U.S House","CD-04"],
    ["Tennessee", "U.S House","CD-05"],
    ["Tennessee", "U.S House","CD-06"],
    ["Tennessee", "U.S House","CD-07"],
    ["Tennessee", "U.S House","CD-08"],
    ["Tennessee", "U.S House","CD-09"],
    ["Tennessee", "U.S Senate","Statewide"],
    ["Tennessee", "Governor","Statewide"],
    ["Tennessee", "Lieutenant Governor","Statewide"],
    ["Tennessee", "Supreme Court","Statewide"],

    ["Texas", "U.S House","CD-01"],
    ["Texas", "U.S House","CD-02"],
    ["Texas", "U.S House","CD-03"],
    ["Texas", "U.S House","CD-04"],
    ["Texas", "U.S House","CD-05"],
    ["Texas", "U.S House","CD-06"],
    ["Texas", "U.S House","CD-07"],
    ["Texas", "U.S House","CD-08"],
    ["Texas", "U.S House","CD-09"],
    ["Texas", "U.S House","CD-10"],
    ["Texas", "U.S House","CD-11"],
    ["Texas", "U.S House","CD-12"],
    ["Texas", "U.S House","CD-13"],
    ["Texas", "U.S House","CD-14"],
    ["Texas", "U.S House","CD-15"],
    ["Texas", "U.S House","CD-16"],
    ["Texas", "U.S House","CD-17"],
    ["Texas", "U.S House","CD-18"],
    ["Texas", "U.S House","CD-19"],
    ["Texas", "U.S House","CD-20"],
    ["Texas", "U.S House","CD-21"],
    ["Texas", "U.S House","CD-22"],
    ["Texas", "U.S House","CD-23"],
    ["Texas", "U.S House","CD-24"],
    ["Texas", "U.S House","CD-25"],
    ["Texas", "U.S House","CD-26"],
    ["Texas", "U.S House","CD-27"],
    ["Texas", "U.S House","CD-28"],
    ["Texas", "U.S House","CD-29"],
    ["Texas", "U.S House","CD-30"],
    ["Texas", "U.S House","CD-31"],
    ["Texas", "U.S House","CD-32"],
    ["Texas", "U.S House","CD-33"],
    ["Texas", "U.S House","CD-34"],
    ["Texas", "U.S House","CD-35"],
    ["Texas", "U.S House","CD-36"],
    ["Texas", "U.S House","CD-37"],
    ["Texas", "U.S House","CD-38"],
    ["Texas", "U.S Senate","Statewide"],
    ["Texas", "Governor","Statewide"],
    ["Texas", "Lieutenant Governor","Statewide"],
    ["Texas", "Attorney General","Statewide"],
    ["Texas", "Commisioner of Agriculture","Statewide"],
    ["Texas", "Comptroller of Public Accounts","Statewide"],
    ["Texas", "Land Commissioner","Statewide"],
    ["Texas", "Railroad Commission","Statewide"],

    ["Utah", "U.S House","CD-01"],
    ["Utah", "U.S House","CD-02"],
    ["Utah", "U.S House","CD-03"],
    ["Utah", "U.S House","CD-04"],
    ["Utah", "U.S Senate","Statewide"],
    ["Utah", "Governor","Statewide"],
    ["Utah", "Lieutenant Governor","Statewide"],
    ["Utah", "Board of Education","D1"],
    ["Utah", "Board of Education","D2"],
    ["Utah", "Board of Education","D4"],
    ["Utah", "Board of Education","D5"],
    ["Utah", "Board of Education","D7"],
    ["Utah", "Board of Education","D8"],
    ["Utah", "Board of Education","D11"],
    ["Utah", "Board of Education","D14"],

    ["Vermont", "U.S House","At-Large"],
    ["Vermont", "U.S Senate","Statewide"],
    ["Vermont", "Governor","Statewide"],
    ["Vermont", "Lieutenant Governor","Statewide"],
    ["Vermont", "Attorney General","Statewide"],
    ["Vermont", "Secretary of State","Statewide"],
    ["Vermont", "Auditor","Statewide"],
    ["Vermont", "Treasurer","Statewide"],

    ["Virginia", "U.S House","CD-01"],
    ["Virginia", "U.S House","CD-02"],
    ["Virginia", "U.S House","CD-03"],
    ["Virginia", "U.S House","CD-04"],
    ["Virginia", "U.S House","CD-05"],
    ["Virginia", "U.S House","CD-06"],
    ["Virginia", "U.S House","CD-07"],
    ["Virginia", "U.S House","CD-08"],
    ["Virginia", "U.S House","CD-09"],
    ["Virginia", "U.S House","CD-10"],
    ["Virginia", "U.S House","CD-11"],
    ["Virginia", "U.S Senate","Statewide"],
    ["Virginia", "Governor","Statewide"],
    ["Virginia", "Lieutenant Governor","Statewide"],
    ["Virginia", "Attorney General","Statewide"],
    ["Virginia", "Secretary of State","Statewide"],
    ["Virginia", "Auditor","Statewide"],
    ["Virginia", "Treasurer","Statewide"],

    ["Washington", "U.S House","CD-01"],
    ["Washington", "U.S House","CD-02"],
    ["Washington", "U.S House","CD-03"],
    ["Washington", "U.S House","CD-04"],
    ["Washington", "U.S House","CD-05"],
    ["Washington", "U.S House","CD-06"],
    ["Washington", "U.S House","CD-07"],
    ["Washington", "U.S House","CD-08"],
    ["Washington", "U.S House","CD-09"],
    ["Washington", "U.S House","CD-10"],
    ["Washington", "U.S Senate","Statewide"],
    ["Washington", "Governor","Statewide"],
    ["Washington", "Lieutenant Governor","Statewide"],
    ["Washington", "Attorney General","Statewide"],
    ["Washington", "Secretary of State","Statewide"],
    ["Washington", "Auditor","Statewide"],
    ["Washington", "Treasurer","Statewide"],

    ["West Virginia", "U.S House","CD-01"],
    ["West Virginia", "U.S House","CD-02"],
    ["West Virginia", "U.S Senate","Statewide"],
    ["West Virginia", "Governor","Statewide"],
    ["West Virginia", "Lieutenant Governor","Statewide"],
    ["West Virginia", "Attorney General","Statewide"],
    ["West Virginia", "Secretary of State","Statewide"],
    ["West Virginia", "Auditor","Statewide"],
    ["West Virginia", "Treasurer","Statewide"],

    ["Wisconsin", "U.S House","CD-01"],
    ["Wisconsin", "U.S House","CD-02"],
    ["Wisconsin", "U.S House","CD-03"],
    ["Wisconsin", "U.S House","CD-04"],
    ["Wisconsin", "U.S House","CD-05"],
    ["Wisconsin", "U.S House","CD-06"],
    ["Wisconsin", "U.S House","CD-07"],
    ["Wisconsin", "U.S House","CD-08"],
    ["Wisconsin", "U.S Senate","Statewide"],
    ["Wisconsin", "Governor","Statewide"],
    ["Wisconsin", "Lieutenant Governor","Statewide"],
    ["Wisconsin", "Attorney General","Statewide"],
    ["Wisconsin", "Secretary of State","Statewide"],
    ["Wisconsin", "Auditor","Statewide"],
    ["Wisconsin", "Treasurer","Statewide"],
    ["Wisconsin", "Supreme Court","Statewide"],

    ["Wyoming", "U.S House","At-Large"],
    ["Wyoming", "U.S Senate","Statewide"],
    ["Wyoming", "Governor","Statewide"],
    ["Wyoming", "Lieutenant Governor","Statewide"],
    ["Wyoming", "Attorney General","Statewide"],
    ["Wyoming", "Secretary of State","Statewide"],
    ["Wyoming", "Auditor","Statewide"],
    ["Wyoming", "Treasurer","Statewide"],
    ["Wyoming", "Superintendent of Public Instruction","Statewide"],
];
/*as a note, the creator I booted this from says this is the difficult way to do this. if I would like to update it with more dropdowns such as 4 or 5, it is 
possible to use classes instead. for now (6/25/26) I got this working and am just going to roll with it. sorry to anyone looking in the future */

function makeDropdown(data,filtersAsArray,targetElement){
    const filteredArray = filterArray(data,filtersAsArray);
    const uniqueList = getUniqueValues(filteredArray, filtersAsArray.length);
    populateDropdown(targetElement, uniqueList);
}

function applyDropdown(){
    const selectState = document.getElementById("State").value;
    const selectOffice = document.getElementById("Office");
    makeDropdown(myData,[selectState],selectOffice);
    applyDropdown2();
}

function applyDropdown2(){
    const selectState = document.getElementById("State").value;
    const selectOffice = document.getElementById("Office").value;
    const selectJurisdiction = document.getElementById("Jurisdiction");
    makeDropdown(myData,[selectState, selectOffice],selectJurisdiction);
}

function onLoad(){
    populateFirstLevelDropdown();
    applyDropdown();
}

function getUniqueValues(data,index){
    const uniqueOptions = new Set();
    data.forEach(r => uniqueOptions.add(r[index]));
    return [...uniqueOptions];
}

function populateFirstLevelDropdown(){
    const uniqueList = getUniqueValues(myData,0);
    const el = document.getElementById("State");
    populateDropdown(el, uniqueList);
}

function populateDropdown(el, listAsArray){
    el.innerHTML = "";
    listAsArray.forEach(item => {
        const option = document.createElement("option");
        option.textContent = item;
        el.appendChild(option);
});
}

function filterArray(data,filtersAsArray){
    return data.filter(r => filtersAsArray.every((item,i) => item === r[i]));
}


document.getElementById("State").addEventListener("change",applyDropdown);
document.getElementById("Office").addEventListener("change",applyDropdown2);
document.addEventListener("DOMContentLoaded", onLoad);



/*var dd = new DropDown(myData).eazyDropDown(["State", "Office","District"]); */